#!/bin/bash
# minimax.sh -  MiniMax + Claude Code

# ===== model API Key =====
MINIMAX_API_KEY="sk-cp-FcQhEAwWQCmozgDUeocsRzatBN03b3gjH4itRPq88TwtbPk-3tUTcOGonOgzYSG0uNDSlooN9w5f7HsDmnBHI8xuM9sZI6TbMbIx-6q5BA10zzNDqGXXpKs"
MINIMAX_BASE_URL="https://api.minimaxi.com/anthropic"
MINIMAX_MODEL="MiniMax-M2.7"
MINIMAX_FAST_MODEL="MiniMax-M2.1"
# ============================

unset ANTHROPIC_API_KEY

export ANTHROPIC_BASE_URL="$MINIMAX_BASE_URL"
export ANTHROPIC_AUTH_TOKEN="$MINIMAX_API_KEY"
export ANTHROPIC_MODEL="$MINIMAX_MODEL"
export ANTHROPIC_DEFAULT_OPUS_MODEL="$MINIMAX_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$MINIMAX_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$MINIMAX_FAST_MODEL"
export ANTHROPIC_SMALL_FAST_MODEL="$MINIMAX_FAST_MODEL"
export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1

echo "Use MiniMax $MINIMAX_MODEL"
exec claude "$@"
